Repository OpenShock/Firmware, pull requests merged in 2023-12, with the labels that each got.

#143 Show compilation warning when no LED implementation is defined
  src/VisualStateManager.cpp
Labels: type: enhancement

#144 Implement sending shocker commands via serial
  include/serialization/JsonSerial.h
  src/SerialInputHandler.cpp
  src/serialization/JsonSerial.cpp
Labels: type: enhancement

#147 Radio code cleanup
  WebUI/src/lib/_fbs/open-shock/serialization/types/shocker-model-type.ts
  include/radio/rmt/CaiXianlinEncoder.h
  include/radio/rmt/PetrainerEncoder.h
  include/radio/rmt/XlcEncoder.h
  include/serialization/_fbs/ShockerModelType_generated.h
  schemas/Types/ShockerModelType.fbs
  src/SerialInputHandler.cpp
  src/radio/rmt/CaiXianlinEncoder.cpp
  src/radio/rmt/MainEncoder.cpp
  src/radio/rmt/PetrainerEncoder.cpp
  src/serialization/JsonAPI.cpp
  src/serialization/JsonSerial.cpp
Labels: type: task

#149 Better checking for shocker types, fix rmt sending causing crashes
  include/ShockerModelType.h
  include/radio/rmt/internal/Shared.h
  src/serialization/JsonAPI.cpp
  src/serialization/JsonSerial.cpp
Labels: type: bug, in: radio, in: api-comms

#150 Move ShockerCommandType FromString logic to common place
  include/ShockerCommandType.h
  src/serialization/JsonSerial.cpp
Labels: in: serial, type: enhancement

#151 Make sure to use OPENSHOCK_TX_PIN when resetting TX Pin
  include/Constants.h
  platformio.ini
  src/CommandHandler.cpp
  src/config/RFConfig.cpp
Labels: in: settings, in: radio, type: enhancement

#152 Update dependencies
  WebUI/package-lock.json
  WebUI/package.json
Labels: type: task

#153 [Feature] Better chip unsafe pin definitions
  include/Board.h
  include/Chipset.h
  include/Constants.h
  scripts/embed_env_vars.py
  src/CommandHandler.cpp
Labels: type: enhancement

#160 Implement AvailGPIO command
  src/SerialInputHandler.cpp
Labels: in: serial, type: enhancement

#161 [Refactoring] SerialInputHandler
  include/serial/SerialInputHandler.h
  src/main.cpp
  src/serial/SerialInputHandler.cpp
Labels: in: serial, type: task

#167 Fix cppcheck warnings and errors
  include/Chipset.h
  include/RGBPatternManager.h
  include/WebSocketDeFragger.h
  include/config/BackendConfig.h
  include/config/RFConfig.h
  include/config/WiFiConfig.h
  include/event_handlers/impl/WSGateway.h
  include/event_handlers/impl/WSLocal.h
  include/http/HTTPRequestManager.h
  include/util/Base64Utils.h
  platformio.ini
  src/CommandHandler.cpp
  src/EStopManager.cpp
  src/GatewayClient.cpp
  src/GatewayConnectionManager.cpp
  src/RGBPatternManager.cpp
  src/VisualStateManager.cpp
  src/WebSocketDeFragger.cpp
  src/config/BackendConfig.cpp
  src/config/CaptivePortalConfig.cpp
  src/config/Config.cpp
  src/config/RFConfig.cpp
  src/config/RootConfig.cpp
  src/config/SerialInputConfig.cpp
  src/config/WiFiConfig.cpp
  src/config/WiFiCredentials.cpp
  src/event_handlers/websocket/local/AccountUnlinkCommand.cpp
  src/event_handlers/websocket/local/SetRfTxPinCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkConnectCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkDisconnectCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkForgetCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkSaveCommand.cpp
  src/event_handlers/websocket/local/WiFiScanCommand.cpp
  src/event_handlers/websocket/local/_InvalidMessage.cpp
  src/http/HTTPRequestManager.cpp
  src/radio/RFTransmitter.cpp
  src/radio/rmt/CaiXianlinEncoder.cpp
  src/radio/rmt/PetrainerEncoder.cpp
  src/serial/SerialInputHandler.cpp
  src/serialization/JsonAPI.cpp
  src/serialization/JsonSerial.cpp
  src/util/Base64Utils.cpp
  src/util/CertificateUtils.cpp
  src/wifi/WiFiManager.cpp
  src/wifi/WiFiNetwork.cpp
  src/wifi/WiFiScanManager.cpp
Labels: type: bug

#165 [Bugfix] xiao pin bypass
  include/Chipset.h
Labels: type: bug
