Repository OpenShock/Firmware, pull requests merged in 2023-11, with the labels that each got.

#79 Locate global python interpreter and pyftsubset programatically
  scripts/build_frontend.py
Labels: type: bug, in: ci, type: enhancement

#87 Improve python workflow for dependencies and building frontend
  platformio.ini
  requirements.txt
  scripts/build_frontend.py
  scripts/install_dependencies.py
Labels: type: optimization, in: ci, type: enhancement

#88 Abandon the abandoned repo 💀
  platformio.ini
Labels: type: bug, dependencies, in: captive-portal

#90 Minor code cleanup
  include/GatewayClient.h
  include/Logging.h
  include/PinPatternManager.h
  include/RFTransmitter.h
  include/SerialHandler.h
  src/CertificateUtils.cpp
  src/Config.cpp
  src/GatewayClient.cpp
  src/GatewayConnectionManager.cpp
  src/MessageHandlers/Local.cpp
  src/MessageHandlers/Server.cpp
  src/PinPatternManager.cpp
  src/RFTransmitter.cpp
  src/SerialInputHandler.cpp
  src/main.cpp
Labels: type: task, priority: low

#91 ci: Add CDN upload
  .github/actions/build-filesystem/action.yml
  .github/actions/cdn-bump-version/action.yml
  .github/actions/cdn-prepare/action.yml
  .github/actions/cdn-upload-board/action.yml
  .github/actions/cdn-upload-version-info/action.yml
  .github/actions/merge-images/action.yml
  .github/workflows/ci-build.yml
  .github/workflows/ci-tag.yml
  .github/workflows/get-targets.yml
  chips/ESP32-D0WD/merge-image.py
  chips/ESP32-D0WDQ6/merge-image.py
  chips/ESP32-S2/N4R2/merge-image.py
  chips/ESP32-S3/N16R8/merge-image.py
  chips/ESP32-S3/N8R8/merge-image.py
Labels: in: ci

#89 Fix HTTP server crashing due to Watchdog timeout
  include/CaptivePortalInstance.h
  scripts/build_frontend.py
  scripts/flatc.exe
  src/CaptivePortalInstance.cpp
Labels: type: bug, in: captive-portal

#93 Some GPIO code cleanup
  include/Board.h
  src/CommandHandler.cpp
  src/SerialInputHandler.cpp
Labels: in: radio, type: task

#94 Fix AsyncStaticWebHandler segfault
  include/CaptivePortalInstance.h
  src/CaptivePortalInstance.cpp
Labels: type: bug, in: captive-portal

#95 Add MDNS support
  .env
  src/CaptivePortal.cpp
Labels: in: captive-portal, in: wifi, type: enhancement

#98 Fix typos
  src/serialization/WSGateway.cpp
  src/serialization/WSLocal.cpp
Labels: type: task

#101 Add http caching with filesystem hash to reduce load on ESP
  scripts/build_frontend.py
  src/CaptivePortalInstance.cpp
Labels: type: optimization, in: captive-portal

#102 Fix serial WiFi configuration not working
  include/Config.h
  include/wifi/WiFiManager.h
  include/wifi/WiFiNetwork.h
  src/Config.cpp
  src/GatewayConnectionManager.cpp
  src/SerialInputHandler.cpp
  src/wifi/WiFiManager.cpp
Labels: type: bug, in: settings, in: serial, in: wifi

#109 Conform EStopManager to code style
  include/EStopManager.h
  src/EStopManager.cpp
Labels: type: task

#113 Fix captive portal not showing network savestate + forget functionality
  WebUI/src/lib/MessageHandlers/WifiNetworkEventHandler.ts
  WebUI/src/lib/MessageHandlers/index.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/device-to-local-message-payload.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/ready-message.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-got-ip-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-lost-ip-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-connected-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-disconnected-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-discovered-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-lost-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-removed-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-saved-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network-updated-event.ts
  WebUI/src/lib/_fbs/open-shock/serialization/types/wifi-network-event-type.ts
  WebUI/src/lib/_fbs/open-shock/serialization/types/wifi-network.ts
  WebUI/src/lib/stores/DeviceStateStore.ts
  include/Config.h
  include/serialization/WSLocal.h
  include/serialization/_fbs/DeviceToLocalMessage_generated.h
  include/serialization/_fbs/WifiNetworkEventType_generated.h
  include/serialization/_fbs/WifiNetwork_generated.h
  include/wifi/WiFiNetwork.h
  schemas/DeviceToLocalMessage.fbs
  schemas/Types/WifiNetwork.fbs
  schemas/Types/WifiNetworkEventType.fbs
  src/Config.cpp
  src/event_handlers/WiFiScan.cpp
  src/serialization/WSLocal.cpp
  src/wifi/WiFiManager.cpp
  src/wifi/WiFiNetwork.cpp
Labels: type: bug, in: captive-portal

#115 Decrease cache to 1 hour
  src/CaptivePortalInstance.cpp
Labels: in: captive-portal, type: task

#106 Rework HTTP/JSON handling to be cleaner
  include/http/HTTPRequestManager.h
  include/http/JsonAPI.h
  include/serialization/JsonAPI.h
  include/util/CertificateUtils.h
  include/util/HexUtils.h
  include/util/JsonRoot.h
  platformio.ini
  src/Config.cpp
  src/GatewayClient.cpp
  src/GatewayConnectionManager.cpp
  src/SerialInputHandler.cpp
  src/event_handlers/websocket/local/WiFiNetworkConnectCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkDisconnectCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkForgetCommand.cpp
  src/event_handlers/websocket/local/WiFiNetworkSaveCommand.cpp
  src/http/HTTPRequestManager.cpp
  src/http/JsonAPI.cpp
  src/serialization/JsonAPI.cpp
  src/serialization/WSLocal.cpp
  src/util/CertificateUtils.cpp
  src/wifi/WiFiNetwork.cpp
Labels: type: optimization, in: serial, in: api-comms

#122 Increase stability by handling heavy tasks better
  include/util/TaskUtils.h
  src/radio/RFTransmitter.cpp
Labels: type: optimization

#123 Remove loop() behaviour from code
  include/CaptivePortalInstance.h
  include/EStopManager.h
  include/util/TaskUtils.h
  include/wifi/WiFiScanManager.h
  src/CaptivePortal.cpp
  src/CaptivePortalInstance.cpp
  src/EStopManager.cpp
  src/main.cpp
  src/wifi/WiFiScanManager.cpp
Labels: type: optimization, type: enhancement

#135 Fix CommandHandler semaphore initialization
  src/CommandHandler.cpp
Labels: type: bug, in: radio

#136 Remove code accidentally embedded in serial print strings
  src/SerialInputHandler.cpp
Labels: type: bug, in: serial

#138 RFTransmitter cleanup
  include/radio/RFTransmitter.h
  src/CommandHandler.cpp
  src/radio/RFTransmitter.cpp
  src/radio/rmt/PetTrainerEncoder.cpp
  src/radio/rmt/XlcEncoder.cpp
Labels: type: task
