Repository OpenShock/Firmware, pull requests merged in 2023-10, with the labels that each got.

#14 Feature/use gzip compression
  build_frontend.py
Labels: enhancement

#16 Start implementing dotenv vars
  .env
  .env.development
  .env.production
  .github/workflows/ci-build.yml
  .gitignore
  .vscode/settings.json
  build_frontend.py
  embed_version.py
  install_boards.py
  platformio.ini
  release_or_develop.py
  scripts/.gitignore
  scripts/build_frontend.py
  scripts/embed_env_vars.py
  scripts/merge_image.py
  scripts/utils/__init__.py
  scripts/utils/conv.py
  scripts/utils/dotenv.py
  scripts/utils/pioenv.py
  scripts/utils/shorthands.py
  scripts/utils/sysenv.py
  src/VisualStateManager.cpp
Labels: enhancement

#17 Fix configuring and connecting to wifi via captive portal
  .clang-format
  WebUI/src/lib/WebSocketClient.ts
  WebUI/src/lib/WebSocketMessageHandler.ts
  WebUI/src/lib/components/WiFiList.svelte
  WebUI/src/lib/components/modals/WiFiDetails.svelte
  WebUI/src/lib/stores/WiFiStateStore.ts
  WebUI/src/lib/types/WiFiNetwork.ts
  WebUI/src/lib/types/WiFiState.ts
  include/AuthenticationManager.h
  include/CaptivePortal.h
  include/Mappers/EspWiFiTypesMapper.h
  include/Utils/HexUtils.h
  include/WiFiCredentials.h
  include/WiFiManager.h
  include/WiFiScanManager.h
  include/WiFiState.h
  src/AuthenticationManager.cpp
  src/CaptivePortal.cpp
  src/Mappers/EspWiFiTypesMapper.cpp
  src/VisualStateManager.cpp
  src/WiFiCredentials.cpp
  src/WiFiManager.cpp
  src/WiFiScanManager.cpp
  src/WiFiState.cpp
  src/main.cpp
Labels: bug

#22 Add support for release candidates
  .github/workflows/ci-tag.yml
Labels: enhancement

#33 build: Add Seeed Xiao ESP32-S3
  .github/workflows/ci-build.yml
  chips/ESP32-D0WD/merge-image.py
  chips/ESP32-D0WD/partitions.csv
  chips/ESP32-D0WDQ6/merge-image.py
  chips/ESP32-D0WDQ6/partitions.csv
  chips/ESP32-S2/N4R2/merge-image.py
  chips/ESP32-S2/N4R2/partitions.csv
  chips/ESP32-S3/N16R8/merge-image.py
  chips/ESP32-S3/N16R8/partitions.csv
  chips/ESP32-S3/N8R8/merge-image.py
  chips/ESP32-S3/N8R8/partitions.csv
  platformio.ini
  scripts/merge_image.py
  scripts/use_openshock_params.py
  scripts/utils/boardconf.py
Labels: board-compatability

#49 Improve millis and micros implementation
  include/GatewayClient.h
  include/Time.h
  src/GatewayClient.cpp
  src/GatewayConnectionManager.cpp
  src/RFTransmitter.cpp
  src/Time.cpp
  src/WiFiManager.cpp
Labels: type: enhancement

#52 Improve command handling
  WebUI/src/lib/_fbs/open-shock/serialization/shocker-command.ts
  include/_fbs/ServerToDeviceMessage_generated.h
  schemas/ServerToDeviceMessage.fbs
  src/MessageHandlers/Server/ShockerCommandList.cpp
  src/RFTransmitter.cpp
Labels: in: radio, in: api-comms, type: enhancement

#57 [bugfix] Fix missing logs
  include/Logging.h
  include/Rmt/MainEncoder.h
  include/Rmt/PetTrainerEncoder.h
  include/Rmt/XlcEncoder.h
  src/CaptivePortal.cpp
  src/CaptivePortalInstance.cpp
  src/CertificateUtils.cpp
  src/CommandHandler.cpp
  src/Config.cpp
  src/GatewayClient.cpp
  src/GatewayConnectionManager.cpp
  src/MessageHandlers/Local.cpp
  src/MessageHandlers/Local/GatewayPairCommand.cpp
  src/MessageHandlers/Local/GatewayUnpairCommand.cpp
  src/MessageHandlers/Local/SetRfTxPinCommand.cpp
  src/MessageHandlers/Local/WiFiNetworkConnectCommand.cpp
  src/MessageHandlers/Local/WiFiNetworkDisconnectCommand.cpp
  src/MessageHandlers/Local/WiFiNetworkForgetCommand.cpp
  src/MessageHandlers/Local/WiFiNetworkSaveCommand.cpp
  src/MessageHandlers/Local/WiFiScanCommand.cpp
  src/MessageHandlers/Local/_InvalidMessage.cpp
  src/MessageHandlers/Server.cpp
  src/MessageHandlers/Server/CaptivePortalConfig.cpp
  src/MessageHandlers/Server/ShockerCommandList.cpp
  src/MessageHandlers/Server/_InvalidMessage.cpp
  src/PinPatternManager.cpp
  src/RFTransmitter.cpp
  src/Rmt/MainEncoder.cpp
  src/SerialInputHandler.cpp
  src/VisualStateManager.cpp
  src/WiFiManager.cpp
  src/WiFiScanManager.cpp
  src/main.cpp
Labels: type: bug, in: logging

#55 [Feature] Implement factory reset functionality
  include/Config.h
  src/Config.cpp
  src/SerialInputHandler.cpp
Labels: in: settings, in: serial, type: enhancement

#62 Remove certificate authorities bundle from LittleFS
  certificates/README.md
  certificates/x509_crt_bundle
  data/.gitkeep
  platformio.ini
  src/CertificateUtils.cpp
Labels: type: optimization

#63 Fix captive portal websocket url resolution
  WebUI/src/lib/WebSocketClient.ts
Labels: type: bug, in: captive-portal

#68 Add automated weekly dependency update workflow
  .github/dependabot.yml
Labels: dependencies, in: ci, type: enhancement

#71 Implement toasts feedback
  WebUI/src/lib/MessageHandlers/index.ts
  WebUI/src/lib/Serializers/SetRfTxPinCommand.ts
  WebUI/src/lib/WebSocketClient.ts
  WebUI/src/lib/_fbs/DeviceToLocalMessage.ts
  WebUI/src/lib/_fbs/WifiAuthMode.ts
  WebUI/src/lib/_fbs/WifiScanStatus.ts
  WebUI/src/lib/_fbs/open-shock.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/device-to-local-message-payload.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/gateway-pair-command-result.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/gateway-pair-result-code.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/ready-message.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/set-rf-pin-result-code.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/set-rf-tx-pin-command-result.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-network.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/wifi-scan-status-message.ts
  WebUI/src/lib/_fbs/open-shock/serialization/types.ts
  WebUI/src/lib/_fbs/open-shock/serialization/types/wifi-auth-mode.ts
  WebUI/src/lib/_fbs/open-shock/serialization/types/wifi-scan-status.ts
  WebUI/src/lib/components/WiFiList.svelte
  WebUI/src/lib/stores/ToastDelegator.ts
  WebUI/src/lib/stores/WiFiStateStore.ts
  WebUI/src/lib/types/WiFiState.ts
  WebUI/src/routes/+layout.svelte
  WebUI/src/routes/+page.svelte
  include/Board.h
  include/CommandHandler.h
  include/GatewayConnectionManager.h
  include/GatewayPairResultCode.h
  include/Mappers/EspWiFiTypesMapper.h
  include/MessageHandlers/Local_Private.h
  include/RFTransmitter.h
  include/SetRfPinResultCode.h
  include/WiFiAuthMode.h
  include/WiFiScanManager.h
  include/WiFiScanStatus.h
  include/_fbs/DeviceToLocalMessage_generated.h
  include/_fbs/WifiAuthMode_generated.h
  include/_fbs/WifiScanStatus_generated.h
  schemas/DeviceToLocalMessage.fbs
  schemas/Types/WifiAuthMode.fbs
  schemas/Types/WifiScanStatus.fbs
  src/CaptivePortalInstance.cpp
  src/CommandHandler.cpp
  src/EventHandlers/WiFiScanEventHandlers.cpp
  src/GatewayConnectionManager.cpp
  src/MessageHandlers/Local/GatewayPairCommand.cpp
  src/MessageHandlers/Local/SetRfTxPinCommand.cpp
  src/RFTransmitter.cpp
  src/WiFiManager.cpp
  src/WiFiScanManager.cpp
Labels: in: captive-portal, type: enhancement, javascript

#72 Misc code cleanup
  .gitignore
  platformio.ini
  src/PinPatternManager.cpp
  src/RFTransmitter.cpp
  src/WiFiManager.cpp
  src/WiFiScanManager.cpp
Labels: type: optimization, type: enhancement

#75 Fix network configuration via serial
  include/Config.h
  src/Config.cpp
  src/SerialInputHandler.cpp
Labels: type: bug, in: settings, in: serial

#76 Better device status reporting at local WS connect
  WebUI/src/lib/MessageHandlers/index.ts
  WebUI/src/lib/_fbs/open-shock/serialization/local/ready-message.ts
  WebUI/src/lib/components/WiFiList.svelte
  WebUI/src/lib/components/modals/WiFiDetails.svelte
  WebUI/src/lib/stores/DeviceStateStore.ts
  WebUI/src/lib/stores/WiFiStateStore.ts
  WebUI/src/lib/stores/index.ts
  WebUI/src/lib/types/WiFiNetwork.ts
  WebUI/src/lib/types/WiFiState.ts
  WebUI/src/routes/+page.svelte
  include/WiFiManager.h
  include/WiFiNetwork.h
  include/_fbs/DeviceToLocalMessage_generated.h
  schemas/DeviceToLocalMessage.fbs
  src/CaptivePortalInstance.cpp
  src/WiFiManager.cpp
  src/WiFiNetwork.cpp
Labels: in: captive-portal, type: enhancement, javascript

#77 Make AP name configurable via .env files
  .env
  src/CaptivePortal.cpp
Labels: in: wifi, type: enhancement
